### ISSUE TITLE
Tabellenformatierung und Reihenfolge

### ISSUE THREAD

**Issue by mschindl** [ModeratorPS/bestellsystem#2]
![image](https://user-images.githubusercontent.com/26382876/222969527-d061b217-0d8a-40ab-a5d8-184f977029cc.jpeg)

**Comment by ModeratorPS** [comment]
Hallo,
danke für die Info. Ich werde mich darum kümmern.
~ ModeratorPS

**Comment by ModeratorPS** [comment]
Ist behoben! Siehe Update 4.2
- ModeratorPS
