### ISSUE TITLE
Komplexe Passwörter in Kurzbefehle zulassen

### ISSUE THREAD

**Issue by mschindl** [ModeratorPS/bestellsystem#3]

**Comment by ModeratorPS** [comment]
Hallo mschindl,
dies ist aktuell noch ein Beta Release und wird wahrscheinlich mit der Version 4.3 veröffentlicht. Ich hoffe, dass ich es bis dann behoben habe.
~ ModeratorPS

**Comment by ModeratorPS** [comment]
Fixed

**Comment by ModeratorPS** [comment]
Hallo mschindl,
das Problem kann nicht behoben werden, da dass Textfeld von Apple eine Funktion ist, die nicht von mir vorgegeben ist.
- ModeratorPS
